# Generated by Django 5.2.3 on 2025-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusModel',
            fields=[
                #('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusid', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('google_maps_link', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'customer_location',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
