# Generated by Django 5.2.3 on 2025-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cusmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusmodel',
            name='cusid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
