# Generated by Django 5.2.3 on 2025-06-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cusmodel_cusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusmodel',
            name='cusid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
