# Generated by Django 5.2.3 on 2025-06-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cusmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusmodel',
            name='user',
        ),
    ]
